### ISSUE TITLE
Controllers with variable names are not annotated

### ISSUE THREAD

**Issue by TiddoLangerak** [olov/ng-annotate#166] opened 2015-05-20 08:27 UTC
When a name of a controller/service/directive comes from a variable it will not be automatically annotated.

### Minimal example:
```javascript
var name = "foo";
angular.module("test", [])
   .controller(name, function($scope){});
```

### Expected result
A properly annotated controller like this:
```javascript
var name = "foo";
angular.module("test", [])
    .controller(name, ["$scope", function($scope) {}]);
```

### Actual result
Nothing changed:
```javascript
var name = "foo";
angular.module("test", [])
    .controller(name, function($scope){});
```

**Comment by olov** [comment] 2015-05-20 08:54
Dupe of #54

**Closed by olov** 2015-05-20 08:54 UTC
