### ISSUE TITLE
Coffeescript support - allowing "ngInject" at any line of the function

### ISSUE THREAD

**Issue by tomca32** [olov/ng-annotate#152] opened 2015-03-27 18:05 UTC
Coffeescript constructor does not allow the "ngInject" directive to be the first line of the function because it first binds the parameters to this.

 Using ### @ngInject ### doesn't work because of variable hoisting.

Here's an [example](http://coffeescript.org/#try:%0Aclass%20SomeClass%0A%20%20%0A%20%20%23%23%23%20%40ngInject%20%23%23%23%0A%20%20constructor%3A%20(%40a%2C%20%40b)%20-%3E%0A%20%20%20%20%22ngInject%22%0A%0A%20%20someVariable%20%3D%201)

ngInject(...) cannot work because it seems to always use the array syntax which is incompatible with classes.

Is it possible to make "ngInject" work even if it isn't the first statement in a function?

**Comment by olov** [comment] 2015-04-01 09:10
(I noticed your PR but figured the discussion should stay here)

I understand how this is problematic for you and I'm not saying no to providing a work-around in ng-annotate for CoffeeScript's bug but let's be clear that this is a bug in CoffeScript and it should primarily be reported and addressed there. Replace `"ngInject"` with another directive prologue literal, say `"use strict"` and it's clear that CS does not do the right thing in terms of preserving directive prologues. The problem is not limited to constructors, take this for an example:

```coffescript
race = (winner, runners...) ->
  "use strict";
  print winner, runners
```

If you're unable to get this addressed in CS then I'll consider adding support for randomly placed directives, behind a flag.

**Comment by olov** [comment] 2015-04-19 18:12
Did you get any feedback from CS authors?

**Comment by olov** [comment] 2015-05-20 17:05
Closing due to lack of feedback.

**Closed by olov** 2015-05-20 17:05 UTC

**Comment by smrq** [comment] 2015-06-09 20:44
For what it's worth, TypeScript also has this issue with its equivalent syntax:

```typescript
class FooService {
    constructor (private $scope: ng.IScope) {
        "ngInject";
    }
}
```

will compile into

```typescript
var FooService = (function () {
    function FooService($scope) {
        this.$scope = $scope;
        "ngInject";
    }
    return FooService;
})();
```

While I agree that this could be interpreted as a bug in both compilers, that's really only technically true if your language of choice supports directive prologues; however, as far as I can tell, they are not part of the [TypeScript language spec (as of 1.4)](http://www.typescriptlang.org/Content/TypeScript%20Language%20Specification.pdf).  In that sense it's a language design fail rather than implementation fail, but that's the present state of things.

**Comment by olov** [comment] 2015-06-09 21:00
That seems like a tsc/spec bug. I filed https://github.com/Microsoft/TypeScript/issues/3454

**Comment by ryoqun** [comment] 2015-12-01 17:29
I've just created an issue regarding this at the CoffeeScript repository: https://github.com/jashkenas/coffeescript/pull/4155

**Comment by olov** [comment] 2015-12-01 19:24
@ryoqun my recommendation would be to push for directive prologue preservation in CoffeeScript, like tsc https://github.com/Microsoft/TypeScript/issues/3454. `"ngInject"` is prefered over `/*@ngInject*/` (documentation will be updated to reflect this).

**Comment by ryoqun** [comment] 2015-12-02 01:43
@olov Thanks for a quick reply.

I know the directive prologue works. However it doesn't offer the same level of flexibility of annotation comments like this taken from ng-annotate's README...

```
obj = /*@ngInject*/ {
    controller: function($scope) {},
    resolve: { data: function(Service) {} },
};
```

Or, could I be overlooking something. Is there  equivalent with the directive prologue?
