### ISSUE TITLE
Error when parsing quoted property names

### ISSUE THREAD

**Issue by Romke-vd-Meulen** [olov/ng-annotate#205] opened 2015-10-29 16:40 UTC
My codebase is building neatly on my dev machine (Ubuntu trusty, node v0.10.40), but on my build server (node v0.12.7) I get this error:

```
node_modules/ng-annotate/ng-annotate-main.js:368
    if ((prop.key.type === "Identifier" && prop.key.name === name) ||
                 ^
TypeError: Cannot read property 'type' of undefined
	at matchProp (node_modules/ng-annotate/ng-annotate-main.js:368:22)
	at matchProviderGet (node_modules/ng-annotate/ng-annotate-main.js:96:46)
	at match (node_modules/ng-annotate/ng-annotate-main.js:44:9)
	at traverse.post (node_modules/ng-annotate/ng-annotate-main.js:1120:23)
	at visit (node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:52:13)
	at visit (node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:46:21)
	at visit (node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:43:25)
	at visit (node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:46:21)
	at visit (node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:43:25)
	at visit (node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:46:21)
```

Both use the npm distributed `ng-annotate@1.0.2`.

I've played around with the input until finally finding that this error only occurs when in this codesnippet:

```
angular.module('myApp').directive("myDirective", function(service) {
        return {
                restrict: 'A',
                require: '^form',
                scope: { "address": "=", countries: "=" },
                // ...
        }
});
```

the scope properties are quoted. When I unquote them, the error goes away. Oddly enough, I have another directive further down in the sourcecode which has quoted property names, but this doesn't seem to affect the outcome.

For now I'll just work around it, but I'd love to know what's causing this behaviour.

**Comment by olov** [comment] 2015-10-29 17:29
I can't reproduce the problem with your example snippet (ng-annotate 1.0.2):

```
~/projects/ng-annotate/tests-issues % cat issue205.js
angular.module('myApp').directive("myDirective", function(service) {
        return {
	    restrict: 'A',
                require: '^form',
                scope: { "address": "=", countries: "=" },
                // ...
		}
    });
~/projects/ng-annotate/tests-issues % ng-annotate -a issue205.js
angular.module('myApp').directive("myDirective", ["service", function(service) {
        return {
	    restrict: 'A',
                require: '^form',
                scope: { "address": "=", countries: "=" },
                // ...
		}
    }]);
~/projects/ng-annotate/tests-issues % ng-annotate
ng-annotate v1.0.2
...

```

Can you verify the input and provide a similar console output please?

**Comment by olov** [comment] 2015-10-29 17:34
Sorry I missed the information you wrote about node v0.12.7. I'll try that!

**Comment by olov** [comment] 2015-10-29 18:04
Possible dupe of #184

**Comment by olov** [comment] 2015-10-30 08:12
Tried your snippet with node 0.12.7 but it still works fine here. I suspect that your provided test case is not complete. Can you please save the test case to a separate file and run it with `ng-annotate -a filename.js`?

**Comment by olov** [comment] 2015-12-01 19:38
Need more info, closing.

**Closed by olov** 2015-12-01 19:38 UTC
