### ISSUE TITLE
directive not annotated unless registered name is hardcoded

### ISSUE THREAD

**Issue by lpfeup** [olov/ng-annotate#191] opened 2015-09-01 12:59 UTC
If I register a directive as:
<code>myApp.directive("myDirective", function(MyService) {...});</code>
it is correctly annotated. 
However, if I pass the name of the directive as a variable:
<code>var myDirectiveName = "myDirective";
myApp.directive(myDirectiveName, function(MyService) {...});</code>

it is not. In this case I need to use @ngInject for it to be annotated:
<code>
myApp.directive(myDirectiveName, /\*@ngInject\*/  function(MyService) {...});
</code>

**Comment by olov** [comment] 2015-09-21 05:37
dupe of #54

**Closed by olov** 2015-09-21 05:37 UTC
