### ISSUE TITLE
Variable at the top of a script stops annotation

### ISSUE THREAD

**Issue by clinington** [olov/ng-annotate#177] opened 2015-06-24 09:49 UTC
I'm not sure if this is a bug, or because of my incorrect usage:

Firing off this command in `cmder`
`λ ng-annotate -a home.controllers.js`

Will produce this code below, as you can see there is no `$inject` with the dependencies.

```javascript                                           
var controllerName = 'HomeController';                                         
                                                                               
angular.module('home.module')                                                  
  .controller(controllerName, homeController);                                 
                                                                               
function homeController($scope) {                                              
  var vm = this;                                                               
                                                                               
  vm.myInterval = 5000;                                                        
  var slides = vm.slides = [];                                                 
                                                                               
  for (var i=0; i<4; i++) {                                                    
    addSlide();                                                                
  }                                                                            
                                                                               
  function addSlide() {                                                        
    var newWidth = 1140 + slides.length + 1;                                   
    slides.push({                                                              
      image: 'http://baconmockup.com/' + newWidth + '/300',                    
      text: ['More','Extra','Lots of','Surplus'][slides.length % 4] + ' ' +    
        ['Bacon', 'Bacon', 'Bacon', 'Bacon'][slides.length % 4]                
    });                                                                        
  }                                                                            
}                                                                              
```

When the variable reference is removed, `ng-annotate` will correctly add dependency injection.

```javascript
angular.module('home.module')
  .controller('HomeController', homeController);

function homeController($scope) {
  var vm = this;

  vm.myInterval = 5000;
  var slides = vm.slides = [];

  for (var i=0; i<4; i++) {
    addSlide();
  }

  function addSlide() {
    var newWidth = 1140 + slides.length + 1;
    slides.push({
      image: 'http://baconmockup.com/' + newWidth + '/300',
      text: ['More','Extra','Lots of','Surplus'][slides.length % 4] + ' ' +
        ['Bacon', 'Bacon', 'Bacon', 'Bacon'][slides.length % 4]
    });
  }
}
homeController.$inject = ["$scope"];
```

**Comment by olov** [comment] 2015-06-24 10:03
dupe of #54

**Closed by olov** 2015-06-24 10:03 UTC
